<a href="https://colab.research.google.com/github/sararotenski/AlgoritmosEProgramacao/blob/main/aula_2904.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Aprendendo Numpy

In [ ]:
#É uma biblioteca que implementa computação científica de alto desempenho no Python.
#-Numpy é parcialmente implementada em C, para performance.
#-Numpy oferece (dentre outros...):
#-Arrays multidimensionais - Otimizações
#-Álgebra linear - Algoritmos de clusterização

In [1]:
!pip install numpy

import numpy as np

In [2]:
list1 = [1, 2, 3, 4]
list1.append('teste')

print(list1)

[1, 2, 3, 4, 'teste']


In [4]:
import numpy as np

var1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

var2 = np.array(var1, dtype=np.int32)

print(var2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
#ndarray
#É a estrutura de dados básica do numpy
#Implementa matrizes com quaisquer dimensões.
#Possuem tipo fixo e tamanho fixo.

In [42]:
#jeito difícil
lst1 = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])

for linha in range(len(lst1)):
  for col in range(len(lst1[linha])):
    lst1[linha][col] = lst1[linha][col] + 1
print(lst1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [43]:
#jeito simples
m = np.full((3, 3), 1)
m2 = m + 1
print(m2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [6]:
#Exercício 1
#Crie uma matriz 3 x 3 do tipo inteiro
#Crie uma matriz 3 x 4 do tipo float32
#Crie uma matriz 5 x 4 do tipo Booleano

matriz1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matriz2 = np.array(matriz1, dtype=np.int32)

print(matriz2)

matriz3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=np.float32)

print(matriz3)

matriz4 = np.array([
    [True, False, True, True],
    [True, False, True, True],
    [True, False, True, True],
    [True, False, True, True],
    [True, False, True, True]
], dtype=np.bool)

print(matriz4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]]


In [7]:
#matriz de zeros 5x5

m1 = np.zeros((5, 5), dtype=np.float32)
print(m1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#Exercício 2
#Crie uma matriz de zeros 3 x 3 do tipo inteiro
#Crie uma matriz de zeros 3 x 4 do tipo float32

m1 = np.zeros((3, 3), dtype=np.int32)
print(m1)

m2 = np.zeros((3, 4), dtype=np.float32)
print(m2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#matriz aleatória

m1 = np.random.random((5, 5))
print(m1)

[[0.04401412 0.48422779 0.05093934 0.40680681 0.35237935]
 [0.25675529 0.44967105 0.65120964 0.98589837 0.20622712]
 [0.98278431 0.94289038 0.34489112 0.4874614  0.58602925]
 [0.29696533 0.81984222 0.90599238 0.09533599 0.85081654]
 [0.7215334  0.34987515 0.27319283 0.23850287 0.59800888]]


In [12]:
#Exercício 3
#Crie uma matriz aleatória com formato 3 x 3

m1 = np.random.random((3, 3))
print(m1)

[[0.14380809 0.3305611  0.98658546]
 [0.91199066 0.64866376 0.10816346]
 [0.24188262 0.35189682 0.28130564]]


In [14]:
#matriz com o mesmo número

m1 = np.full((5, 5), 3)
print(m1)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [16]:
#lendo um elemento
#m1[linha, coluna]

m1 = np.random.random((5, 5))

print(m1)
print(m1[0, 0])
print(m1[1, 0])
print(m1[1, 1])

[[0.34213571 0.2740969  0.41102773 0.29930145 0.77800617]
 [0.78782323 0.46607762 0.62879352 0.79591519 0.97239303]
 [0.53400531 0.41275135 0.00613743 0.70532373 0.880506  ]
 [0.04880239 0.83273704 0.08762979 0.07731902 0.28756766]
 [0.03991171 0.22325334 0.65726371 0.95955388 0.92986778]]
0.3421357133572336
0.7878232268785099
0.46607761904678413


In [21]:
#alterando um elemento

m1 = np.zeros((5, 5))

m1[0, 0] = 1
m1[0, 1] = 2

print(m1)

[[1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
#Exercício 4
#Crie uma matriz aleatória com formato 3 x 3
#Altere a primeira linha e coluna para o valor 10.0

m1 = np.random.random((3, 3))
print(m1)

m1[0, 0] = 10.0
print(m1)

[[0.78599274 0.46108028 0.77710789]
 [0.93503686 0.45671148 0.03380717]
 [0.20122068 0.26762654 0.3913623 ]]
[[10.          0.46108028  0.77710789]
 [ 0.93503686  0.45671148  0.03380717]
 [ 0.20122068  0.26762654  0.3913623 ]]


In [26]:
#operação com escalar

m1 = np.zeros((5, 5))
m1 = m1 + 3
print(m1)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [29]:
#Exercício 5
#Crie uma matriz aleatória com formato 3 x 3 com números de 0 a 100

m1 = np.random.random((3, 3))
m1 = m1 * 100
print(m1)

[[95.97754821 92.00200795 13.5033999 ]
 [10.73111543  9.58693316 27.45279582]
 [32.04286119 77.94858814 90.28530401]]


In [31]:
#somando matrizes

m1 = np.full((5, 5), 3.2)
m2 = np.full((5, 5), 2.3)
print(m1 + m2)

[[5.5 5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5 5.5]
 [5.5 5.5 5.5 5.5 5.5]]


In [32]:
#subtraindo matrizes

m1 = np.full((5, 5), 3.2)
m2 = np.full((5, 5), 2.3)
print(m1 - m2)

[[0.9 0.9 0.9 0.9 0.9]
 [0.9 0.9 0.9 0.9 0.9]
 [0.9 0.9 0.9 0.9 0.9]
 [0.9 0.9 0.9 0.9 0.9]
 [0.9 0.9 0.9 0.9 0.9]]


In [44]:
#Exercício 6
#Crie duas matrizes aleatórias com formato 3 x 3 com números de
#0 a 100
#Apresente a soma e a diferença entre elas.

m1 = np.random.random((3, 3))
m1 = m1 * 100
m2 = np.random.random((3, 3))
m2 = m2 * 100

print(m1)
print(m2)
print(f'Soma: {m1 + m2}')
print(f'Subtração: {m1 - m2}')

[[40.04124654 94.5926003  52.94811894]
 [24.60435648 94.72421438 11.89137279]
 [24.2997285  24.35024656 68.2158995 ]]
[[46.48833075 65.23188006 69.60075777]
 [58.14351986 81.61837565 81.66172377]
 [50.73582652 52.12477745 35.39260886]]
Soma: [[ 86.5295773  159.82448036 122.54887671]
 [ 82.74787634 176.34259003  93.55309656]
 [ 75.03555501  76.47502401 103.60850836]]
Subtração: [[ -6.44708421  29.36072025 -16.65263883]
 [-33.53916337  13.10583872 -69.77035099]
 [-26.43609802 -27.77453089  32.82329063]]


In [46]:
#multiplicando matrizes

m1 = np.full((5, 5), 3)
m2 = np.full((5, 5), 4)
print(m1 @ m2)

[[60 60 60 60 60]
 [60 60 60 60 60]
 [60 60 60 60 60]
 [60 60 60 60 60]
 [60 60 60 60 60]]


In [47]:
#Exercício 7
#Crie duas matrizes aleatórias com formato 3 x 3 com números de
#0 a 100
#Apresente a multiplicação entre as matrizes

m1 = np.random.random((3, 3))
m1 = m1 * 100
m2 = np.random.random((3, 3))
m2 = m2 * 100

print(m1 @ m2)

[[10576.89218467  6583.99520068  7758.13818741]
 [ 8338.57841417  4298.09729847  6433.9686293 ]
 [ 6447.3339422   4966.06432936  7052.51055638]]
