<a href="https://colab.research.google.com/github/sararotenski/AlgoritmosEProgramacao/blob/main/aula_0605.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Continuação - Numpy

In [6]:
!pip install numpy

import numpy as np

In [13]:
#invertendo matrizes
m1 = np.array([
    [1, 4, 3],
    [2, 7, 5],
    [7, 4, 9]
])

m2 = np.linalg.inv(m1)
print(m2)

[[-3.58333333  2.          0.08333333]
 [-1.41666667  1.         -0.08333333]
 [ 3.41666667 -2.          0.08333333]]


In [14]:
#encontrando o determinante
det = np.linalg.det(m1)
print(det)

-12.00000000000001


In [1]:
#propriedades
#ndim - ranking ou número de dimensões
#size - número de elementos
#shape - formato
#dtype - tipo de dados

In [20]:
#reshaping
m1 = np.full((4, 4), 5.0)
m2 = m1.reshape(((8, 2))) #shallow copy
m3 = m1.reshape((2, 8)) #shallow copy
print(m2)
print(m3)

[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]
[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [21]:
#os ndarrays não são copiados
m1 = np.full((4, 4), 5.0)
m2 = m1
m2[0, 0] = 10.0
print(m1)

[[10.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]]


In [22]:
#copiando uma matriz
m1 = np.full((4, 4), 5.0)
m2 = m1.copy() #deep copy
m2[0, 0] = 10.0
print(m1)
print(m2)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[10.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]]


In [30]:
#filtrando a matriz com uma matriz de booleanos
m1 = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [1, 2, 3, 4]
])
m2 = np.array([
    [True, False, False, False],
    [True, False, False, False],
    [True, False, False, False]
])
print(m1[m2])

[ 1 -1  1]


In [28]:
#filtrando a matriz com uma matriz de booleanos
m1 = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [1, 2, 3, 4]
])
print(m1 > 1)

[[False  True  True  True]
 [False False False False]
 [False  True  True  True]]


In [29]:
#filtrando a matriz com uma matriz de booleanos
m1 = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [1, 2, 3, 4]
])
print(m1 == 1)

[[ True False False False]
 [False False False False]
 [ True False False False]]


In [31]:
#filtrando a matriz com uma matriz de booleanos
m1 = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [1, 2, 3, 4]
])
print((m1 == 1) | (m1 == -1))

[[ True False False False]
 [ True False False False]
 [ True False False False]]


In [32]:
#filtrando a matriz com uma matriz de booleanos
m1 = np.array([
    [1, 2, 3, 4],
    [-1, -2, -3, -4],
    [1, 2, 3, 4]
])
print(m1[m1 > 1])

[2 3 4 2 3 4]
